[build]
  base = "client"
  publish = "dist"
  command = "pnpm install && pnpm build"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"
  PNPM_VERSION = "8.15.6" # or whatever version you're using
